name: qr_project_skl_3
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.0+2
  device_preview: ^1.2.0
  flutter:
    sdk: flutter
  mobile_scanner: ^6.0.2
  permission_handler: ^11.3.1
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

fonts:
  - family: Manrope
    fonts:
      - asset: assets/fonts/Manrope-Regular.ttf
      # - asset: assets/fonts/muli/Muli-Bold.ttf
      #   weight: 700
      # - asset: assets/fonts/muli/Muli-Light.ttf
      #   weight: 300
